package org.cy.core.test;

import java.util.Date;

import org.cy.core.jdbc.JdbcTemplate;
import org.cy.core.jdbc.JdbcTemplateFactory;
import org.cy.core.jdbc.TransactionManager;

public class Test{
	
	private String logInfo;
	
	private Date logDate;
	
	public static void main(String[] args) throws Exception {
		TransactionManager transactionManager = new TransactionManager();
		JdbcTemplate template = JdbcTemplateFactory.getJdbcTemplate(transactionManager.getConnection());
		Test test = new Test();
		test.setLogInfo("哈哈神马都是浮云");
		test.setLogDate(new Date());
		Long id = template.insertGetGeneratedValueByBean("insert into t_logger_info(log_info,log_date) values(:logInfo,:logDate)",test);
		int id2 = template.getAutoGeneratedValue().intValue();
		System.out.println(id);
		System.out.println(id2);
		transactionManager.commit();
		transactionManager.close();
	}

	public String getLogInfo() {
		return logInfo;
	}

	public void setLogInfo(String logInfo) {
		this.logInfo = logInfo;
	}

	public Date getLogDate() {
		return logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}
	
}
