INSERT INTO t_system_resource_info VALUES ('1', 'RES_EXAMPLE_USER', '/example/user/**', '账户管理');
INSERT INTO t_system_resource_info VALUES ('2', 'RES_EXAMPLE_ROLE', '/example/role/**', '角色管理');
INSERT INTO t_system_resource_info VALUES ('3', 'RES_EXAMPLE_RESOURCE', '/example/resource/**', '权限管理');
INSERT INTO t_system_resource_info VALUES ('4', 'RES_EXAMPLE_TEMPLATE', '/example/template/**', '模板管理');
INSERT INTO t_system_resource_info VALUES ('5', 'RES_EXAMPLE_INDEX', '/example/index.htm', '演示首页');
INSERT INTO t_system_resource_info VALUES ('6', 'RES_EXAMPLE_TASK', '/example/task/**', '任务调度');
INSERT INTO t_system_resource_info VALUES ('7', 'RES_EXAMPLE_REPORT', '/example/report/**', '报表统计');
INSERT INTO t_system_resource_info VALUES ('8', 'RES_EXAMPLE_SEARCH', '/example/search/**', '搜索引擎');
INSERT INTO t_system_resource_info VALUES ('9', 'RES_EXAMPLE_LOGGER', '/example/logger/**', '日志管理');
INSERT INTO t_system_role_info VALUES ('1', 'ADMIN', '管理员');
INSERT INTO t_system_role_info VALUES ('2', 'TEMPLATOR', '模板制作专员');
INSERT INTO t_system_role_info VALUES ('3', 'LOOKER', '预览系统');
INSERT INTO t_system_role_info VALUES ('4', 'SEO', '搜索引擎优化');
INSERT INTO t_system_role_resource VALUES ('2', '4');
INSERT INTO t_system_role_resource VALUES ('2', '5');
INSERT INTO t_system_role_resource VALUES ('2', '8');
INSERT INTO t_system_role_resource VALUES ('3', '5');
INSERT INTO t_system_role_resource VALUES ('3', '7');
INSERT INTO t_system_role_resource VALUES ('3', '8');
INSERT INTO t_system_role_resource VALUES ('1', '1');
INSERT INTO t_system_role_resource VALUES ('1', '2');
INSERT INTO t_system_role_resource VALUES ('1', '3');
INSERT INTO t_system_role_resource VALUES ('1', '4');
INSERT INTO t_system_role_resource VALUES ('1', '5');
INSERT INTO t_system_role_resource VALUES ('1', '6');
INSERT INTO t_system_role_resource VALUES ('1', '7');
INSERT INTO t_system_role_resource VALUES ('1', '8');
INSERT INTO t_system_role_resource VALUES ('1', '9');
INSERT INTO t_system_role_resource VALUES ('4', '5');
INSERT INTO t_system_role_resource VALUES ('4', '8');
INSERT INTO t_system_role_resource VALUES ('4', '9');
INSERT INTO t_system_user_info VALUES ('1', 'admin', 'ceb4f32325eda6142bd65215f4c0f371', '系统管理员', 'admin@springexample.com', '1', '1', '1', '1');
INSERT INTO t_system_user_info VALUES ('2', 'user', '47a733d60998c719cf3526ae7d106d13', '模板专员', 'user@example.com', '1', '1', '1', '1');
INSERT INTO t_system_user_info VALUES ('3', 'caoyang', '8caddd773172975a1e093dac8c18e249', '曹阳', 'caoyang@126.com', '1', '1', '1', '1');
INSERT INTO t_system_user_info VALUES ('4', 'tanchang', 'ed629c177564f7199977bac371d1f714', '谭畅', 'tanchang@163.com', '1', '1', '1', '1');
INSERT INTO t_system_user_info VALUES ('5', 'xielei', '1980cdc901388cf43b04f0347a85f690', '谢雷', 'xielei@ow.com', '1', '1', '1', '1');
INSERT INTO t_system_user_info VALUES ('6', 'douzhi', 'ccba99c64767285b2f2c5bb8488030e7', '窦志', 'douzhi@ow.com', '1', '1', '1', '1');
INSERT INTO t_system_user_info VALUES ('7', 'zhangdi', '45d2478c44b950a487c1bbd3e3f4c38f', '张迪', 'zhangdi@ow.com', '1', '1', '1', '1');
INSERT INTO t_system_user_info VALUES ('8', '赵磊', 'e95a7469e2a823e561cc8fc161380d0e', '赵磊', '赵磊@1.com', '1', '1', '1', '1');
INSERT INTO t_system_user_info VALUES ('9', '陈涛', '75586ac60001d3375657cf17a3f73237', '陈涛', '陈涛@2.b', '1', '1', '1', '1');
INSERT INTO t_system_user_role VALUES ('1', '1');
INSERT INTO t_system_user_role VALUES ('2', '2');
INSERT INTO t_system_user_role VALUES ('4', '3');
INSERT INTO t_system_user_role VALUES ('5', '3');
INSERT INTO t_system_user_role VALUES ('7', '3');
INSERT INTO t_system_user_role VALUES ('8', '3');
INSERT INTO t_system_user_role VALUES ('9', '3');
INSERT INTO t_system_user_role VALUES ('6', '3');
INSERT INTO t_system_user_role VALUES ('3', '1');
INSERT INTO t_system_user_role VALUES ('3', '2');
INSERT INTO t_system_user_role VALUES ('3', '3');
INSERT INTO t_system_user_role VALUES ('3', '4');
INSERT INTO t_task_info VALUES ('3', '任务A', '2009-12-08 17:00:01', '0', '0', 'testTaskA', '任务A');
INSERT INTO t_task_info VALUES ('4', '任务B', '2009-11-03 17:00:01', '0', '0', 'testTaskB', '任务B');
INSERT INTO t_task_info VALUES ('5', '任务C', '2009-12-08 17:00:01', '0', '0', 'testTaskC', '任务C');