package org.paramecium.jdbc.dialect;

import java.sql.Connection;
import java.sql.SQLException;
/**
 * 功 能 描 述:<br>
 * Informix数据库方言实现
 * <br>代 码 作 者:曹阳(CaoYang)
 * <br>开 发 日 期:2011-3-30下午03:16:27
 * <br>项 目 信 息:paramecium:org.paramecium.jdbc.dialect.InformixDialect.java
 */
public final class InformixDialect extends BaseDialect implements Dialect {

	public String getSql(final String sql,Page page){
		String querySql=sql;
		if (page.isFirstSetted()&&page.isPageSizeSetted()) {
			querySql="SELECT SKIP "+page.getFirst()+" FIRST "+page.getFirst()+page.getPageSize()+" "+querySql.substring(7, querySql.length());
		}
		return querySql;
	}
	
	public Number getAutoGeneratedKey(final Connection connection) throws SQLException {
		throw new SQLException("该数据库没有相关方法!请手动调用getAutoGeneratedKey(String sql)方法.推荐语句：SELECT dbinfo('sqlca.sqlerrd1') FROM <TABLE>");
	}

	public Number getAutoGeneratedKey(final Connection connection,final String sql) throws SQLException {
		if(sql==null){
			return getAutoGeneratedKey(connection);
		}
		return (Number) queryUniqueColumnValue(connection,sql);
	}
	
	
}
